"""
BankSentinel — WebSocket Routes
=================================
WebSocket endpoint for live alert streaming to connected dashboards.

WS /ws/alerts — Push new alerts as they're generated
"""

import asyncio
import json
import logging
import time
from datetime import datetime, timezone
from typing import List, Set

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

router = APIRouter(tags=["WebSocket"])

logger = logging.getLogger(__name__)


# ── Connection Manager ────────────────────────────────────────────────────────

class AlertConnectionManager:
    """Manages active WebSocket connections for alert streaming."""

    def __init__(self):
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        logger.info(
            f"WebSocket client connected. "
            f"Active connections: {len(self.active_connections)}"
        )

    def disconnect(self, websocket: WebSocket):
        if websocket in self.active_connections:
            self.active_connections.remove(websocket)
        logger.info(
            f"WebSocket client disconnected. "
            f"Active connections: {len(self.active_connections)}"
        )

    async def broadcast(self, message: dict):
        """Send a message to all connected clients."""
        disconnected = []
        for connection in self.active_connections:
            try:
                await connection.send_json(message)
            except Exception:
                disconnected.append(connection)

        for conn in disconnected:
            self.disconnect(conn)

    @property
    def connection_count(self) -> int:
        return len(self.active_connections)


# Module-level manager
alert_manager = AlertConnectionManager()


# ── WebSocket Endpoint ────────────────────────────────────────────────────────

@router.websocket("/ws/alerts")
async def websocket_alerts(websocket: WebSocket):
    """
    WebSocket endpoint for live alert streaming.

    Clients connect and receive real-time alert notifications
    as they are generated by the pipeline. Messages are JSON objects
    with alert metadata.

    The connection also accepts commands from the client:
    - {"type": "ping"} → responds with {"type": "pong"}
    - {"type": "subscribe", "channel": "..."} → future use
    """
    await alert_manager.connect(websocket)

    # Send welcome message with server state
    try:
        await websocket.send_json({
            "type": "connected",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "message": "Connected to BankSentinel alert stream",
            "active_connections": alert_manager.connection_count,
        })
    except Exception:
        alert_manager.disconnect(websocket)
        return

    try:
        while True:
            # Listen for client messages
            data = await websocket.receive_text()
            try:
                msg = json.loads(data)
                if msg.get("type") == "ping":
                    await websocket.send_json({
                        "type": "pong",
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                    })
            except json.JSONDecodeError:
                pass

    except WebSocketDisconnect:
        alert_manager.disconnect(websocket)


# ── Broadcast helper (called by pipeline routes) ──────────────────────────────

async def broadcast_alert(alert_data: dict):
    """
    Broadcast an alert to all connected WebSocket clients.

    Call this from the pipeline route after processing a flow record.
    """
    message = {
        "type": "alert",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "data": alert_data,
    }
    await alert_manager.broadcast(message)
